# Generated by Django 4.1.3 on 2022-11-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='networth',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
