# Generated by Django 4.1.3 on 2022-11-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedette', '0002_alter_vip_networth'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
