# Generated by Django 4.1.3 on 2022-11-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedette', '0003_vip_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vip',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
