# Generated by Django 4.1.3 on 2022-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedette', '0004_alter_vip_age_alter_vip_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='vip_score',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
