# Generated by Django 4.1.3 on 2022-11-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedette', '0005_vip_vip_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='vip_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
